name: Checkers - Quality

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

permissions:
  contents: read
  id-token: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.8.4"
      - name: Install
        run: poetry install --with dev
      - name: Checkers
        run: make checkers