name: Release Publication
on:
  release:
    types:
      - edited
      - published

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          poetry_version: "==1.8.4"
          python_version: "3.10"
          pypi_token: ${{ secrets.PYPI_PASSWORD }}