name: Release Publication
on:
  release:
    types:
      - edited
      - published

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          poetry_version: "==1.8.1"
          python_version: "3.9"
          pypi_token: ${{ secrets.PYPI_PASSWORD }}