name: Sphinx - Documentation
on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  document:
    runs-on: ubuntu-latest
    steps:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.8.4"
      - name: Install
        run: poetry install --with documenters
      - name: Documenters
        run: make documenters
      - name: Create .nojekyll file
        run: touch docs/build/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/build/